// This file was generated by Prisma, and assumes you have installed the following:
// pnpm install --save-dev dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

console.log(process.env["DATABASE_URL"])

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
